<div class="error-page">
    <h2 class="headline text-info"> <b>404</b></h2>
    <div class="error-content">
        <h3><i class="fa fa-warning text-yellow"></i> <b>Oops! Endereço não encontrado.</b></h3>
        <p>
            Não foi possível localizar a página que você estava procurando. 
            Enquanto isso, você pode retornar para a <a href="<?php echo \Core\FrontController::getController(); ?>">Página Inicial</a> 
            ou tente usar o formulário de busca.
        </p>
        <form class='search-form'>
            <div class='input-group'>
                <input type="text" name="search" class='form-control' placeholder="Search"/>
                <div class="input-group-btn">
                    <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                </div>
            </div><!-- /.input-group -->
        </form>
    </div><!-- /.error-content -->
</div><!-- /.error-page -->