<div class="row">
    <div class="col-md-7">
        
    </div><!-- /.col -->

    <div class="col-md-5">
        <!-- Info box -->
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title"><b>Implant! Framework</b></h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-primary btn-sm" data-widget="collapse" data-toggle="tooltip" title="Minimizar/Maximizar"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-primary btn-sm" data-widget="remove" data-toggle="tooltip" title="Fechar"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <p><h4>Bem vindo(a),</h4></p>
                <p>
                    Pensando em um Framework especializado no desenvolvimento de aplicações de negócio (sistemas de gestão), o Implant! Framework 
                    foi desenvolvido por <a href="https://github.com/LeoFelipe"><b>Leonardo Felipe</b></a> para acelerar a criação desse tipo de 
                    aplicação e fornecer uma arquitetura pronta para o desenvolvimento de sistemas web em PHP sem precisar se preocupar com 
                    Autenticação, ACL, Logs e Template.
                </p>
                <p>
                    O Implant! Framework é um framework baseado em Orientação à Objetos, que utiliza o Design Patterns (Padrões de Projeto) 
                    conhecido como MVC (Model, View e Controller), Front Controller e o Bootstrap 3. O Template utilizado foi uma adaptação,
                    feita pelo autor do Implant! Framework, do projeto <a href="https://github.com/almasaeed2010/AdminLTE"><b>AdminLTE</b></a>.
                </p>
                <p>
                    Desta forma, o Desenvolvedor que utilizar o Implant! Framework para desenvolver aplicações de negócio, apenas focará no 
                    desenvolvimento dos Módulos específicos reduzindo os custos de desenvolvimento e auxiliando desenvolvedores a escreverem 
                    menos código-fonte.
                </p>
                <p>Navegue pelos ícones ao lado ou utilize o menu lateral para administrar a sessão desejada.</p>
                <p>Em caso de dúvidas e/ou problemas técnicos entrar em contato.</p>
                <p>E-mail: <a href="mailto:leonardo.gmail.com">leonardo.gmail.com</a></p>
                <p>Tel.: (79) 9999-6088</p>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->