<div class="box-body table-responsive">
    <table id="dinamicTable" class="table table-hover table-bordered table-striped table-condensed">
        <thead>
            <tr>
                <th width="10%">ID</th>
                <th>GRUPO</th>
                <th width="10%">STATUS</th>
                <th width="10%">OPÇÕES</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($view_actions as $action) : 
                    
                if ($action->getStatus() == 1) {
                    $imgStatus = '<img title="Ativo" src="'.IMG.'icons/active.png">';
                } else {
                    $imgStatus = '<img title="Inativo" src="'.IMG.'icons/inactive.png">';
                }
            ?>
                <tr>
                    <td><?php echo $action->getId(); ?></td>
                    <td><?php echo $action->getNome(); ?></td>
                    <td align="center"><?php echo $imgStatus; ?></td>
                    <td align="center">
                        <a class="btn btn-sm2 btn-warning" title="Editar ID <?php echo $action->getId(); ?>" 
                           href="<?php echo \Implant\FrontController::getController()."/editar/id/{$action->getId()}"; ?>">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        <a class="btn btn-sm2 btn-danger" title="Excluir ID <?php echo $action->getId(); ?>" 
                           href="<?php echo \Implant\FrontController::getController()."/excluir/id/{$action->getId()}"; ?>"
                           onclick="return confirm('Deseja realmente excluir o ID <?php echo $action->getId(); ?> ?');">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <th>ID</th>
                <th>GRUPO</th>
                <th>STATUS</th>
                <th>OPÇÕES</th>
            </tr>
        </tfoot>
    </table>
</div><!-- /.box-body -->