<form role="form" id="form" name="form" action="<?php echo ROOT . \Implant\FrontController::getControllerActionParams(); ?>" method="POST">
    <div class="row">
        <div class="col-md-4">
            <div class="box-body">
                <div class="form-group">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" readonly value="<?php echo $view_grupos->getId(); ?>">
                </div>
                <div class="form-group">
                    <label for="nome">Nome do Grupo</label>
                    <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome do grupo" value="<?php echo $view_grupos->getNome(); ?>">
                </div>
                <div class="form-group">
                    <label for="status">Status</label>
                    <select class="form-control" id="status" name="status">
                        <option value="1" <?php echo ($view_grupos->getStatus() == 1) ? 'selected' : ''; ?>>Ativo</option>
                        <option value="0" <?php echo ($view_grupos->getStatus() == 0) ? 'selected' : ''; ?>>Inativo</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-4">
            <div class="box-footer">
                <button type="submit" class="btn btn-primary center-block">Salvar</button>
            </div>
        </div>
    </div>
</form>